export enum  CascaderTypes {
  SET_CLIENT_ORDER_CREATION="SET_CLIENT_ORDER_CREATION",
  SET_PRICE_ORDER_CREATION="SET_PRICE_ORDER_CREATION",
  SET_MATERIAL="SET_MATERIAL",
  SET_ORDER_VIEW="SET_ORDER_VIEW",
  ADD_NEW_PRICE_ITEM="ADD_NEW_PRICE_ITEM",
  SET_CLIENT_GRAPH="SET_CLIENT_GRAPH"

}